# Generated by Django 4.2.26 on 2025-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
