# Generated by Django 4.2.26 on 2025-12-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_recommendation_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='getting_started',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='how_to_apply',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='interview_prep',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
