# Generated by Django 4.2.26 on 2025-12-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_recommendation_getting_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='generation_source',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user_rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user_rating_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
